project:
  type: website

website:
  title: "thedatavist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd

format:
  html:
    theme: lumo
    css: styles.css
    toc: true



