---
title: "thedatavist"

subtitle: "Analytics & Data Engineering / Data Visusalisation & BI / Data Profession"

format:
  lumo-html: 
    logo: "logo.png"                             # Optional. Path to a logo displayed above the title
    github-repo: "https://github.com/thedatavist/thedatavist_web"        # Optional. Adds a github corner at the top right
    primary-color: "black"
    self-contained: true
    is-particlejs-enabled: true                  # Optional: display interactive particles in the document header
author: Darragh Murray
date: last-modified
---
Hi, I'm Darragh Murray  - a data professional with a pragmatic approach to business intelligence and analytics who runs **datavist.ai**. 

I'm a three-time Tableau Ambassador, a Power BI wizard, an SQL maven, and an analytics engineering expert, who's learned that mastery beats brand loyalty every time. Here, I share insights on data visualization, BI tools, analytics & data engineering and the fundamentals that actually matter in turning data into decisions.

While I build out my new website with more, hopefully interesting, content, you're welcome to stick around and have a read. 

I do recommend checking out the [blog section](https://thedatavist.netlify.app/posts)!

I have also updated my [about me](https://thedatavist.netlify.app/about) section with some recent information along with contact details. 

You're more than welcome to [connect with me on LinkedIn](https://www.linkedin.com/in/darraghmurray/). 