[build]
  command = """
    curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb && \
    dpkg -x quarto-linux-amd64.deb . && \
    ./opt/quarto/bin/quarto render
  """
  publish = "_site"

[build.environment]
  QUARTO_PRINT_STACK = "true"
